#---------------------------------#
#            Rock RMS             #
#---------------------------------#

# version format
version: 1.3.{build}

# increment flag
pull_requests:
  do_not_increment_build_number: true

# Do not build on tags (GitHub only)
skip_tags: true

# operating system (build VM template)
image: Visual Studio 2019
configuration: Release
platform: Any CPU

# clone directory and depth
clone_depth: 1
clone_folder: C:\projects\Rock

# directories to preserve between builds
cache:
#- node_modules
#- packages

# scripts to run before build
# (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.4.4/nuget.exe', "$nugetDir\NuGet.exe")
before_build:
- ps: >-
    (Get-Content "C:\projects\Rock\RockWeb\web.config").Replace('<compilation debug="true"', '<compilation debug="false"') | Set-Content "C:\projects\Rock\RockWeb\web.config"
    
    Install-Product node 16
# build configuration
build:
  project: Rock.sln
  publish_wap: true
  parallel: true
  verbosity: minimal

build_script:
- cmd: >-
    nuget restore
    
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\devenv" "c:\projects\Rock\rock.sln" /build Release
# flag to stop building if an error throws
matrix:
  fast_finish: true

# test
test:
  assemblies:
    only:
      - Rock.Tests.dll

# IIS artifact configuration
artifacts:
- path: RockWeb
  name: RockKit
