//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Rock.CodeGeneration project
//     Changes to this file will be lost when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// <copyright>
// Copyright by the Spark Development Network
//
// Licensed under the Rock Community License (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.rockrms.com/license
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// </copyright>
//

import { CommunicationPreference } from "@Obsidian/Enums/Blocks/Crm/FamilyPreRegistration/communicationPreference";
import { Guid } from "@Obsidian/Types";
import { BirthdayPickerBag } from "@Obsidian/ViewModels/Controls/birthdayPickerBag";
import { PublicAttributeBag } from "@Obsidian/ViewModels/Utility/publicAttributeBag";

export type FamilyPreRegistrationPersonBag = {
    attributes?: Record<string, PublicAttributeBag> | null;

    attributeValues?: Record<string, string> | null;

    birthDate?: BirthdayPickerBag | null;

    communicationPreference: CommunicationPreference;

    email?: string | null;

    ethnicityGuid?: Guid | null;

    firstName?: string | null;

    gender: number;

    lastName?: string | null;

    mobilePhone?: string | null;

    mobilePhoneCountryCode?: string | null;

    raceGuid?: Guid | null;

    suffixDefinedValueGuid?: Guid | null;
};
